<?php

/**
 * @file
 * Contains welcome.module
 * 
 * Code originally created by Drupal Console via the following command:
 *   drupal generate:module --learning
 *   
 * The "module.module" file contains any hooks that interrupt or alter
 * default (core) processing or behavior.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 * 
 * Displays help for the welcome module via the admin help page.
 */
function welcome_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the welcome module.
    case 'help.page.welcome':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a friendly welcome message when user logs in.') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_user_login().
 * 
 * This hook is called when a user logs in.
 */
function welcome_user_login($account) {
  # get the configuration with the module's configuration name:
  $config = \Drupal::config('welcome.adminsettings');
  
  # Get the value of "welcome_message" property with the get method
  # then, display the admin configuration setting to the page:
  drupal_set_message($config->get('welcome_message'));
}