<?php

/**
 * @file
 * Contains welcome.module
 * 
 * Code originally created by Drupal Console via the following command:
 *   drupal generate:module --learning
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function welcome_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the welcome module.
    case 'help.page.welcome':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Display a friendly welcome message when user logs in.') . '</p>';
      return $output;

    default:
  }
}
